manifest = "96b864e1dfa55e5bba53e13ce1d67ea9aee9ff4faebc4fcbe7c00a908a845658"

[[dependency]]
package = "github.com/buckaroo-pm/luadist-libjpeg"
target = "//:jpeg"

[[dependency]]
package = "github.com/buckaroo-pm/madler-zlib"
target = "//:zlib"

[lock."github.com/buckaroo-pm/luadist-libjpeg"]
versions = [ "branch=master" ]
revision = "ca608f3c842d921fa369e798b114c42444f5791d"

[lock."github.com/buckaroo-pm/madler-zlib"]
versions = [ "branch=master" ]
revision = "81e58039a82d50f9c7768c651dce21834557aec1"
