targets = [ "//:tiff" ]

[[dependency]]
package = "github.com/buckaroo-pm/luadist-libjpeg"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/madler-zlib"
version = "branch=master"
