manifest = "2cd5a6a31e81d6d9c7315d3a7a8b71db87203e4449437512ad479e3e3936dfb8"

[[dependency]]
package = "github.com/buckaroo-pm/luadist-libjpeg"
target = "//:jpeg"

[[lock]]
name = "github.com/buckaroo-pm/luadist-libjpeg"
revision = "5e6a7dc7789af950e90b00b13ce36c099dc57bb5"
